<a href="https://colab.research.google.com/github/GabrielaRguezCampos/GabrielaRguezCampos/blob/main/PyTorch_Workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![image](https://www.economist.com/cdn-cgi/image/width=1424,quality=80,format=auto/content-assets/images/20240224_CUP002.jpg)

- [AI Guild Slides](https://docs.google.com/presentation/d/1v924nMVH63ZyNlUxrhKm3v-5kHN9850irJFnsEcgEPc/edit?usp=sharing)
- [Notion](https://exciting-belief-005.notion.site/ai-guild-home)

```
Credits: Gabriel Hübner and David Ulloa
```

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

# The Torch Tensor

A **`torch.Tensor`** is the fundamental data structure in PyTorch, similar to NumPy arrays but with additional capabilities like GPU support and automatic differentiation.


### Automatic Differentiation

![image](https://upload.wikimedia.org/wikipedia/commons/a/a4/ForwardAccumulationAutomaticDifferentiation.png)

#### **Tensor properties**

The **type** of a tensor is the type of each element contained in the tensor:

In [ ]:
t = torch.rand((3, 3))
t.dtype

torch.float32


The **shape** of a tensor is a tuple of integers giving the size of the tensor along each dimension, e.g. for a matrix $M \in \mathbb{R}^{3 \times 5}$:

In [ ]:
t = torch.rand((3,5))
t.shape

torch.Size([3, 5])

The **device** of a tensor indicates the memory in which the tensor currently resides: RAM (denoted as ``cpu``) or GPU memory (denoted as ``cuda``)

In [ ]:
t = torch.rand((3,5))
t.device

device(type='cpu')

# Speaking the NumPy Language

## Tensor Creation

In [ ]:
# Basic tensor creation from python lists
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
torch.zeros((3,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
torch.ones((2,5), dtype=torch.float64)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

 From which distribution these random numbers are sampled? Check the PyTorch documentation

In [ ]:
torch.rand((2,2), )

tensor([[0.3789, 0.8440],
        [0.9264, 0.8940]])

In [ ]:
torch.randint(0, 100, (3,3))

tensor([[86, 24, 97],
        [51, 98,  5],
        [26, 76, 81]])

In [ ]:
torch.arange(0, 100, 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
torch.linspace(0, 100, 51)[:-1]

tensor([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
         24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,
         48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,
         72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,
         96.,  98., 100.])

## Reshaping/Manipulating

In [ ]:
x = torch.rand((3,4))
x, x.shape

(tensor([[0.0275, 0.4841, 0.8763, 0.5368],
         [0.8641, 0.3755, 0.3834, 0.4298],
         [0.2517, 0.1095, 0.5788, 0.2522]]),
 torch.Size([3, 4]))

In [ ]:
# Must have equal number of items
x.reshape(1, 12) # so... 3x4 = 12x1

tensor([[0.0275, 0.4841, 0.8763, 0.5368, 0.8641, 0.3755, 0.3834, 0.4298, 0.2517,
         0.1095, 0.5788, 0.2522]])

In [ ]:
# We can use a -1 to "infer" dimensions
x.reshape(-1, 6) # ?x6 = 3x4, the answer is 2

tensor([[0.0275, 0.4841, 0.8763, 0.5368, 0.8641, 0.3755],
        [0.3834, 0.4298, 0.2517, 0.1095, 0.5788, 0.2522]])

In [ ]:
# We can also flatten our tensor
x.flatten(), x.reshape(-1), x.view(-1) # all do the same thing

(tensor([0.0275, 0.4841, 0.8763, 0.5368, 0.8641, 0.3755, 0.3834, 0.4298, 0.2517,
         0.1095, 0.5788, 0.2522]),
 tensor([0.0275, 0.4841, 0.8763, 0.5368, 0.8641, 0.3755, 0.3834, 0.4298, 0.2517,
         0.1095, 0.5788, 0.2522]),
 tensor([0.0275, 0.4841, 0.8763, 0.5368, 0.8641, 0.3755, 0.3834, 0.4298, 0.2517,
         0.1095, 0.5788, 0.2522]))

In [ ]:
x = torch.randn(1, 3, 1, 4)
print("Before squeeze...", x.shape)

# We can remove any dimension of size 1 using .squeeze()
y = x.squeeze()
print("After squeeze...", y.shape)

# But we can add them back using .unsqueeze()
print("Unsqueezing...", y.unsqueeze(0).unsqueeze(2).shape)

Before squeeze... torch.Size([1, 3, 1, 4])
After squeeze... torch.Size([3, 4])
Unsqueezing... torch.Size([1, 3, 1, 4])


#### 📖 **What `reshape` is really doing?**



Think of the `reshape` operation as unrolling the tensor **row-wise**, to obtain a rank-1 tensor *(matlab users: matlab unrolls **column-wise**, pay attention when converting code!)*. Then organize the values in this tensor following the specified dimensions.

```python
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
```
$-$ unrolling $ \to $

```python
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
```

Then, reading the target shape from right to left, organize the values into the dimensions:

- e.g. reshape into `[4, 3]`:

```python
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
```

$-$ organize in groups of $3$ $ \to $

```python
tensor([[0,  1,  2],  [3,  4,  5],  [6,  7,  8],  [9, 10, 11]])
```

$-$ organize in groups of $4$ $ \to $

```python
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

# same shape of corresponding transpose but it **is** different
```

- e.g. reshape into `[2, 2, 3]`:

```python
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
```

$-$ organize in groups of $3$ $ \to $

```python
tensor([[0,  1,  2],  [3,  4,  5],  [6,  7,  8],  [9, 10, 11]])
```

$-$ organize in groups of $2$ $ \to $

```python
tensor([[[0,  1,  2],  [3,  4,  5]],  [[6,  7,  8],  [9, 10, 11]]])
```

$-$ organize in groups of $2$ $ \to $

```python
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
```

In [ ]:
a = torch.arange(12)
print(a)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [ ]:
a.reshape(6, 2)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [ ]:
a.reshape(2, 6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [ ]:
a.reshape(2, 2, 3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [ ]:
try:
  a.reshape(5, -1)
except RuntimeError as e:
  print('Error:', e)

Error: shape '[5, -1]' is invalid for input of size 12


In [ ]:
a.reshape(1, -1)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [ ]:
a.reshape(-1, 1)

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])

In [ ]:
a.reshape(-1)  # we are flattening the rank-k tensor into a rank-1 tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

> **NOTE**
>
> We can add or remove dimensions of size `1` using `torch.unsqueeze` or `torch.squeeze`

In [ ]:
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.unsqueeze(0).shape

torch.Size([1, 12])

In [ ]:
a.unsqueeze(-1).shape

torch.Size([12, 1])

## Math Operations

**Broadcasting** is a powerful feature in PyTorch (inspired by NumPy) that allows **tensors of different shapes** to be used together in arithmetic operations **without explicitly reshaping them**.
When performing element-wise operations (like addition, subtraction, etc.), **PyTorch automatically expands the smaller tensor** to match the shape of the larger one, **without copying data**. This is called **implicit broadcasting**.


In [ ]:
import torch

# Tensor + Scalar (scalar is broadcasted)
tensor = torch.tensor([1, 2, 3])
result = tensor + 5    # Broadcasting 5 to [5, 5, 5]

print(result)          # Output: [6, 7, 8]

tensor([6, 7, 8])


## Matrix Multiplication and Linear Algebra

In [ ]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

In [ ]:
result = torch.matmul(A, B)
result

tensor([[19, 22],
        [43, 50]])

In [ ]:
A @ B

tensor([[19, 22],
        [43, 50]])

In [ ]:
torch.mm(A, B)

tensor([[19, 22],
        [43, 50]])

In [ ]:
torch.einsum('bchw,jk->ik', A, B)

tensor([[19, 22],
        [43, 50]])

### Batch Matrix Multiplication

In [ ]:
A_batch = A.unsqueeze(0)  # Shape: (1, 2, 2)
B_batch = B.unsqueeze(0)  # Shape: (1, 2, 2)

In [ ]:
result = torch.bmm(A_batch, B_batch)
result = result.squeeze(0)  # Shape: (2, 2)
result

tensor([[19, 22],
        [43, 50]])

### Matrix Vector Multiplication

In [ ]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
v = torch.tensor([1, 0, -1])

result = torch.matmul(A, v)
print(result)

tensor([-2, -2])


## Reductions

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

### Sum

In [ ]:
torch.sum(tensor, dim=0)

tensor([5, 7, 9])

In [ ]:
torch.sum(tensor, dim=1)

tensor([ 6, 15])

### Mean

In [ ]:
torch.mean(tensor.float())

tensor(3.5000)

In [ ]:
torch.mean(tensor.float(), dim=0)

tensor([2.5000, 3.5000, 4.5000])

### Product

In [ ]:
torch.prod(tensor)

tensor(720)

### Max & Min

In [ ]:
max_val, max_indices = torch.max(tensor, dim=1)
max_val, max_indices

(tensor([3, 6]), tensor([2, 2]))

In [ ]:
min_val = torch.min(tensor)
min_val

tensor(1)

### Std Dev. and Variance

In [ ]:
std_dev = torch.std(tensor.float())
variance = torch.var(tensor.float())
std_dev, variance

(tensor(1.8708), tensor(3.5000))

In [ ]:
std_dev ** 2

tensor(3.5000)

## Slicing

In [ ]:
tensor = torch.tensor([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

print("Original Tensor:")
print(tensor)

# 1. Basic Slicing
first_row = tensor[0]
print("\nFirst Row:")
print(first_row)

Original Tensor:
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

First Row:
tensor([1, 2, 3, 4, 5])


In [ ]:
# 2. Slicing a Range of Rows
# Selecting rows 1 to 2 (index 1 to 3, exclusive of 3)
rows_1_to_2 = tensor[1:3]
print("\nRows 1 to 2:")
print(rows_1_to_2)



Rows 1 to 2:
tensor([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])


In [ ]:
# 3. Selecting Specific Columns
# Selecting all rows, but only the second column (index 1)
second_column = tensor[:, 1]
print("\nSecond Column:")
print(second_column)


Second Column:
tensor([ 2,  7, 12, 17])


In [ ]:
# 4. Selecting a Submatrix
# Selecting rows 1 to 3 and columns 2 to 4
submatrix = tensor[1:4, 2:5]
print("\nSubmatrix (rows 1 to 3, columns 2 to 4):")
print(submatrix)


Submatrix (rows 1 to 3, columns 2 to 4):
tensor([[ 8,  9, 10],
        [13, 14, 15],
        [18, 19, 20]])


In [ ]:
# 5. Using Step in Slicing
# Selecting every other row
every_other_row = tensor[::2]
print("\nEvery Other Row:")
print(every_other_row)


Every Other Row:
tensor([[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15]])


In [ ]:
# 6. Advanced Slicing with Negative Indices
# Selecting the last two columns
last_two_columns = tensor[:, -2:]
print("\nLast Two Columns:")
print(last_two_columns)


Last Two Columns:
tensor([[ 4,  5],
        [ 9, 10],
        [14, 15],
        [19, 20]])


In [ ]:
# 7. Combining Indexing and Slicing
# Selecting the element in the 2nd row and 3rd column
specific_element = tensor[1, 2]
print("\nSpecific Element (2nd row, 3rd column):")
print(specific_element)


Specific Element (2nd row, 3rd column):
tensor(8)


### Boolean Indexing

In [ ]:
a = torch.arange(6).reshape(3, 2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
bool_idx = (a > 2)
bool_idx

tensor([[False, False],
        [False,  True],
        [ True,  True]])

## Stacking/Concatenating

In [ ]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

In [ ]:
concat_dim0 = torch.cat((A, B), dim=0)
concat_dim1 = torch.cat((A, B), dim=1)

In [ ]:
concat_dim0, concat_dim1

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 tensor([[1, 2, 5, 6],
         [3, 4, 7, 8]]))

In [ ]:
stack_dim0 = torch.stack((A, B), dim=0)
stack_dim1 = torch.stack((A, B), dim=1)

In [ ]:
stack_dim0, stack_dim1

(tensor([[[1, 2],
          [3, 4]],
 
         [[5, 6],
          [7, 8]]]),
 tensor([[[1, 2],
          [5, 6]],
 
         [[3, 4],
          [7, 8]]]))

In [ ]:
hstack = torch.hstack((A, B))  # Equivalent to cat along dim=1
vstack = torch.vstack((A, B))

In [ ]:
hstack, vstack

(tensor([[1, 2, 5, 6],
         [3, 4, 7, 8]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]))

## Gradient Operations

In [ ]:
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)
b = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.int32)

In [ ]:
c = a * b

No gradients below, because we didn't specify we wanted gradients

In [ ]:
print(c.grad)

None


In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float16, requires_grad=True)
b = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.float16, requires_grad=True)


In [ ]:
# Element wise multiplication
c = a * b

In [ ]:
c

tensor([[ 7., 16., 27.],
        [40., 55., 72.]], dtype=torch.float16, grad_fn=<MulBackward0>)

In [ ]:
s = c.sum()

### Calling .backward populates .grad

In [ ]:
s.backward()

In [ ]:
print(a.grad)
print(b.grad)

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float16)
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)


In [ ]:
print(s.item())

217.0


 From which distribution these random numbers are sampled? Check the PyTorch documentation

In [ ]:
torch.rand((2,2))

tensor([[0.1648, 0.2418],
        [0.1751, 0.6557]])

In [ ]:
torch.randint(0, 100, (3,3))

tensor([[31, 51, 73],
        [20, 25, 42],
        [53,  0, 64]])

# Neural Network Layers

In [ ]:
from torch.nn import Linear, Sequential, Conv2d, MaxPool2d, Flatten, Dropout

In [ ]:
class SimpleNet(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, output_size)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.2)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x


# Loss Functions

In [ ]:
from torch.nn import MSELoss, CrossEntropyLoss, L1Loss, SmoothL1Loss, KLDivLoss

### Mean Squared Error (MSE) Loss
$$L_{\text{MSE}} = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2
$$
### Cross Entropy Loss
$$L_{\text{CE}} = -\sum_{i=1}^{n} y_i \log(\hat{y}_i)
$$
### L1 Loss (Mean Absolute Error)
$$L_{\text{L1}} = \frac{1}{n} \sum_{i=1}^{n} |y_i - \hat{y}_i|
$$

### Kullback-Leibler (KL) Divergence Loss
$$L_{\text{KL}} = \sum_{i=1}^{n} y_i \log\left(\frac{y_i}{\hat{y}_i}\right)
$$

# Activation Functions

In [ ]:
from torch.nn.functional import relu, sigmoid, tanh, softmax

In [ ]:
class SimpleNet(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = relu(self.fc1(x)) # Using ReLU activation after the first linear layer
        x = sigmoid(self.fc2(x)) # Using Sigmoid activation after the second linear layer
        return x

# Optimizers
![image](https://i.sstatic.net/qAx2i.gif)

In [ ]:
from torch.optim import Adam, SGD, AdamW

In [ ]:
# optimizer = Adam(model.parameters(), lr=0.001)
# optimizer = SGD(model.parameters(), lr=0.001)
# optimizer = AdamW(model.parameters(), lr=0.001)

In [ ]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.fc1 = nn.Linear(32 * 8 * 8, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 32 * 8 * 8)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model = CNN()
criterion = nn.CrossEntropyLoss()
optimizer = Adam(model.parameters(), lr=0.001)

input_tensor = torch.randn(1, 3, 32, 32) # Example input
target_tensor = torch.randint(0, 10, (1,)) # Example target

# output = model(input_tensor)
# loss = criterion(output, target_tensor)

# optimizer.zero_grad()
# loss.backward() # Compute gradients
# optimizer.step()


# Einops

In [ ]:
from einops import rearrange

In [ ]:
# A 2D tensor (6, 4)
x = torch.arange(24).reshape(6, 4)
print("Original Shape:", x.shape)

# Reshape to (2, 3, 4)
y = rearrange(x, '(b c) d -> b c d', b=2, c=3)
print("Rearranged Shape:", y.shape)


Original Shape: torch.Size([6, 4])
Rearranged Shape: torch.Size([2, 3, 4])


### Transposing without .permute()

In [ ]:
x = torch.randn(3, 4)
y = rearrange(x, 'h w -> w h')

### Repeating Tensors

In [ ]:
from einops import repeat

In [ ]:
# A simple tensor (shape: [2])
x = torch.tensor([1, 2])

# Repeat to create a matrix (shape: [2, 4])
y = repeat(x, 'b -> b repeat', repeat=4)

print(y)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]])


### Reducing (i.e. Global Average Pooling)


In [ ]:
from einops import reduce

# Tensor simulating feature maps: (Batch=2, Channels=3, Height=4, Width=4)
feature_maps = torch.randn(2, 3, 4, 4)

# Global Average Pooling over spatial dimensions (Height & Width)
pooled = reduce(feature_maps, 'b c h w -> b c', 'mean')

print("Original Shape:", feature_maps.shape)
print("Pooled Shape:", pooled.shape)

Original Shape: torch.Size([2, 3, 4, 4])
Pooled Shape: torch.Size([2, 3])


# Exercises

> Create a matrix $M \in \mathbb{R}^{3 \times 3}$ that is filled with 2 along the diagonal and 1 elsewhere, that is:
>
> $$
m_{ij} =
\begin{cases}
2 & \text{if } i = j \\
1 & \text{otherwise}
\end{cases}
$$

In [ ]:
import torch

In [ ]:
# 2 1 1
# 1 2 1
# 1 1 2

m = torch.ones((3,3))
m = m + torch.eye(3)
m

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [ ]:
# @title 👀 Solution


torch.ones((3,3)) + torch.eye(3)

> Given a matrix $X \in \mathbb{R}^{m \times n}$, create another matrix $Y \in \mathbb{R}^{m \times 3}$ filled with ones using $X$.

In [ ]:
# Exercise variables
x = torch.rand(100,42)

# Your solution:
# y = ?


In [ ]:
# @title 👀 Solution


torch.ones((x.shape[0], 3))

> Without looking at the slides, create the code to compute the gradients with respect to this computation graph. Treat `y = 2.0`to compute the actual difference.
![image](https://media5.datahacker.rs/2021/01/57-1024x821.jpg)

In [ ]:
# @title 👀 Solution
x = torch.tensor(1.0, requires_grad=True) # Input feature
y = torch.tensor(2.0)                     # Actual output
w = torch.tensor(5.0, requires_grad=True) # Weight
b = torch.tensor(1.0, requires_grad=True) # Bias

# Forward pass
u = x * w               # Linear transformation
ŷ = u + b               # Adding bias
e = ŷ - y               # Error calculation
L = e ** 2              # Loss function (squared error)

# Backward pass
L.backward()

# Displaying gradients (only of the leaf nodes)
print(f'dJ/dw = {w.grad}')
print(f'dJ/db = {b.grad}')
print(f'dJ/dx = {x.grad}')

# Extra: Using The GPU

In [ ]:
# Check if the GPU is available
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [ ]:
t = torch.rand((3,3))
# Pay attention to re-assign the variable!
t = t.to(device)
t

tensor([[0.0779, 0.5657, 0.2421],
        [0.6341, 0.3090, 0.5518],
        [0.5896, 0.6568, 0.5754]], device='cuda:0')

In [ ]:
# Construct it directly in the GPU
t = torch.ones((5, 5), device='cuda')
t

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

In [ ]:
# Be careful of hardcoded cuda calls: the code will not run if a GPU is not available
t = t.cuda()
t

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

In [ ]:
t = t.cpu()
t

tensor([[0.0779, 0.5657, 0.2421],
        [0.6341, 0.3090, 0.5518],
        [0.5896, 0.6568, 0.5754]])